name: "Social Media Content Suite"
category: "Content Marketing"
difficulty: "Intermediate"
estimated_tokens: "1000-1500"
version: "1.2.0"

description: "Transform expert interviews into a comprehensive social media campaign that spans multiple platforms and maximizes reach. Perfect for extracting maximum value from interview content across all social channels."

metadata:
  industry: "Social Media Marketing"
  use_cases:
    - "Interview promotion"
    - "Expert content amplification"
    - "Multi-platform campaigns"
    - "Thought leadership"
    - "Audience engagement"
    - "Content repurposing"

  target_audience:
    - "Social media managers"
    - "Content creators"
    - "Marketing teams"
    - "Podcast producers"
    - "Personal brands"

  prerequisites:
    - "Expert interview transcript"
    - "Understanding of brand voice"
    - "Knowledge of platform requirements"
    - "Social media posting tools"

  outputs:
    - "Platform-specific content"
    - "Visual content suggestions"
    - "Engagement strategies"
    - "Cross-platform campaigns"

prompt_template: |
  Transform this expert interview into a comprehensive social media content suite spanning multiple platforms and post types:

  ## LinkedIn Strategy

  ### Carousel Post Series (5-7 slides)
  **Topic:** [Main interview theme]
  **Slide 1:** Hook slide with surprising statistic or question
  **Slide 2-5:** Key insights broken into digestible points
  **Final Slide:** Call-to-action and contact information

  ### Professional Video Post
  **Format:** 60-90 second video with key quote overlay
  **Script:** [Brief script highlighting best soundbite]
  **Visual Elements:** Professional background, quote graphics
  **Caption:** Context and discussion starter

  ### Thought Leadership Article Post
  **Angle:** Industry perspective on interview topic
  **Length:** 300-500 words
  **Structure:** Problem → Expert insight → Industry implication → Call for discussion

  ## Instagram Strategy

  ### Stories Series (8-10 stories)
  **Story 1:** "Just dropped" announcement with guest photo
  **Stories 2-7:** Key quotes with branded backgrounds
  **Stories 8-9:** Behind-the-scenes content
  **Story 10:** "Swipe up" or link directive

  ### Reel Concept
  **Hook:** [Attention-grabbing opening line]
  **Format:** Quick-cut highlights with text overlay
  **Music:** [Trending audio that fits content]
  **Hashtags:** Mix of trending and niche tags

  ### Feed Post Series
  **Post 1:** Guest introduction with professional photo
  **Post 2:** Quote graphic with key insight
  **Post 3:** Carousel with actionable tips from interview

  ## Twitter/X Strategy

  ### Twitter Thread (8-12 tweets)
  **Tweet 1:** Hook tweet with thread indicator
  **Tweets 2-10:** Bite-sized insights from interview
  **Final Tweet:** Conclusion and link to full interview

  ### Individual Tweet Ideas (5-7 standalone tweets)
  - Surprising statistic from interview
  - Contrarian take mentioned by guest
  - Tool/resource recommendation
  - Behind-the-scenes observation
  - Quote tweet opportunity with guest

  ## YouTube Strategy

  ### Short-Form Video (60 seconds)
  **Concept:** [Best moment from interview]
  **Hook:** Question that draws viewers in
  **Structure:** Problem → Solution → Result
  **CTA:** Subscribe and link to full interview

  ### Community Post
  **Poll Question:** Based on interview topic
  **Discussion Starter:** Ask audience for their experiences
  **Resource Share:** Link to related content from interview

  ## TikTok Strategy

  ### Educational Video
  **Format:** Quick tips or "things they don't tell you"
  **Hook:** [Pattern interrupt or surprising fact]
  **Value Points:** 3-5 quick insights from interview
  **Trending Elements:** Current sounds or formats

  ## Cross-Platform Campaign Elements

  ### Visual Branding
  - Color scheme and font recommendations
  - Logo placement guidelines
  - Quote graphic templates
  - Consistent visual style

  ### Hashtag Strategy
  - Platform-specific hashtag research
  - Branded hashtag creation
  - Community hashtag identification
  - Trending hashtag opportunities

  ### Engagement Tactics
  - Question prompts for comments
  - Poll ideas for each platform
  - User-generated content opportunities
  - Cross-platform conversation starters

  Please ensure all content maintains brand voice while being optimized for each platform's unique audience and algorithm preferences.

  Expert interview transcript:
  [PASTE YOUR TRANSCRIPT HERE]

example_input: "Interview with digital marketing expert discussing SEO trends, content strategy, and algorithm changes affecting small businesses."

example_output: |
  ## LinkedIn Strategy

  ### Carousel Post Series: "5 SEO Myths Killing Your Rankings"
  **Slide 1:** "Your SEO strategy might be 5 years out of date 😱"
  **Slide 2:** "Myth #1: Keyword density still matters (Spoiler: It doesn't)"
  **Slide 3:** "Truth: User intent beats keyword stuffing every time"
  **Slide 4:** "Myth #2: More backlinks = better rankings"
  **Slide 5:** "Truth: Quality and relevance trump quantity"
  **Final Slide:** "Want the full breakdown? Listen to my interview with [Expert] →"

  ### Professional Video Post
  **Script:** "I just learned something that completely changed how I think about SEO. [Expert Name] told me that 73% of small businesses are still optimizing for keywords instead of user intent. Here's why that's costing them thousands in lost traffic..."
  **Visual:** Split screen with host and key quote overlay
  **Caption:** "Mind-blown 🤯 Had an incredible conversation with [Expert] about the SEO mistakes that are quietly killing small business websites. The statistics are shocking, but the solutions are surprisingly simple."

  ## Instagram Strategy

  ### Stories Series
  **Story 1:** Guest photo with "Just went live with this SEO genius 🔥"
  **Story 2:** Quote: "Keyword stuffing is like showing up to a dinner party in a tuxedo"
  **Story 3:** Stat overlay: "73% of small businesses are doing SEO wrong"
  **Story 4:** Behind-the-scenes: Recording setup photo
  **Story 5:** "Biggest takeaway" with user intent explanation

  ### Reel Concept
  **Hook:** "POV: You've been doing SEO wrong for 5 years"
  **Quick cuts showing:**
  - Old way: Keyword stuffing example
  - New way: User intent focus
  - Results: Traffic increase graphic
  **Trending audio:** "Oh No" sound for the reveal

best_practices:
  - "Platform optimization: Tailor content format and tone to each platform's unique culture and audience expectations"
  - "Cross-pollination: Reference other platforms and content to create a cohesive brand experience"
  - "Engagement focus: Prioritize content that starts conversations rather than just broadcasting information"
  - "Value consistency: Ensure every post provides standalone value while supporting overall campaign goals"

automation:
  api_compatible: true
  batch_processing: true
  output_format: "multi_platform_campaign"

  integration_examples:
    - name: "Social Media Scheduler"
      description: "Auto-schedule content across multiple platforms"
      code_snippet: |
        social_suite = generate_social_media_suite(transcript)
        scheduler.bulk_schedule(social_suite, posting_calendar)

    - name: "Visual Content Generator"
      description: "Auto-create graphics and visual elements"
      code_snippet: |
        content_suite = create_social_content(transcript)
        visuals = generate_branded_graphics(content_suite)
        design_tool.create_templates(visuals)

resources:
  blog_post: "https://brasstranscripts.com/blog/content-marketing-ai-toolkit-interview-optimization-prompts#prompt-2-social-media-content-suite"
  guide: "https://brasstranscripts.com/ai-prompt-guide"
  upload: "https://brasstranscripts.com/upload"

tags:
  - "social-media-marketing"
  - "multi-platform-content"
  - "content-repurposing"
  - "interview-promotion"
  - "engagement-strategy"
  - "brand-amplification"
  - "social-media-campaigns"