name: "Video Content Strategy"
category: "Content Marketing"
difficulty: "Advanced"
estimated_tokens: "1100-1600"
version: "1.2.0"

description: "Transform expert interviews into comprehensive video content strategies across multiple platforms. Perfect for maximizing the visual content potential of interview insights through strategic video planning and execution."

metadata:
  industry: "Video Marketing"
  use_cases:
    - "YouTube channel strategy"
    - "Video podcast promotion"
    - "Short-form video content"
    - "Educational video series"
    - "Interview repurposing"
    - "Multi-platform video campaigns"

  target_audience:
    - "Video content creators"
    - "YouTube creators"
    - "Video marketers"
    - "Podcast producers"
    - "Content strategists"

  prerequisites:
    - "Expert interview transcript"
    - "Video production capabilities"
    - "Understanding of video platforms"
    - "Knowledge of target audience"

  outputs:
    - "Multi-platform video strategy"
    - "Video series concepts"
    - "Platform-specific optimizations"
    - "Content calendar framework"

prompt_template: |
  Based on this expert interview, create a comprehensive video content strategy that maximizes reach and engagement across multiple video platforms:

  ## YouTube Long-Form Strategy

  ### Main Interview Video
  **Title:** [SEO-optimized title with keyword and hook]
  **Description Template:**
  - Compelling opening paragraph with key benefit
  - Timestamp breakdown of major topics
  - Guest bio and credentials
  - Resource links mentioned in interview
  - Channel subscription CTA
  **Thumbnail Concept:** [Description of eye-catching thumbnail design]
  **Tags:** [10-15 relevant YouTube tags]

  ### Derived Long-Form Videos (3-5 additional videos)
  **Video 1:** Deep dive on main insight
  **Video 2:** "How to implement [strategy]" tutorial
  **Video 3:** "Mistakes to avoid" compilation
  **Video 4:** Tool/resource review mentioned in interview
  **Video 5:** Follow-up Q&A based on audience comments

  ## YouTube Shorts Strategy

  ### Short-Form Concepts (8-10 videos)
  - **Hook-Based Shorts:** Start with surprising statistics
  - **Quote Highlights:** Best soundbites from interview
  - **Quick Tips:** Actionable advice in 60 seconds
  - **Myth-Busting:** Correct common misconceptions
  - **Behind-the-Scenes:** Interview prep or reactions

  **Optimization Elements:**
  - Vertical format optimization
  - Text overlay for silent viewing
  - Strong hooks in first 3 seconds
  - Clear CTAs to full interview

  ## TikTok Strategy

  ### Content Pillars
  **Education:** Quick lessons from interview insights
  **Entertainment:** Relatable scenarios based on interview topics
  **Inspiration:** Motivational moments from guest stories
  **Behind-the-Scenes:** Interview process and preparation

  ### Specific Video Ideas
  - "Things [Expert] taught me about [topic]"
  - "Red flags [Expert] watches for"
  - "Plot twist: [Counterintuitive insight]"
  - "Day in the life of [Expert's role]"

  ## Instagram Video Strategy

  ### Reels Concepts
  **Educational Reels:** Step-by-step processes from interview
  **Trending Audio Reels:** Match insights to popular sounds
  **Before/After Reels:** Show transformation possibilities
  **Quote Reels:** Key insights with visual text overlay

  ### IGTV/Long-Form
  **Mini-Documentaries:** 5-10 minute deep dives on interview topics
  **Tutorial Series:** Extended how-to content
  **Guest Takeover:** Let expert share more insights

  ## LinkedIn Video Strategy

  ### Professional Content
  **Industry Insights:** Business implications of interview topics
  **Career Advice:** Professional development angles
  **Leadership Lessons:** Management and strategy insights
  **Trend Analysis:** Industry predictions and commentary

  ### Native Video Optimization
  - Professional thumbnail images
  - Captions for silent viewing
  - Business-focused messaging
  - Thought leadership positioning

  ## Cross-Platform Video Campaign

  ### Content Hierarchy
  **Tier 1:** Full interview (YouTube main channel)
  **Tier 2:** Topic-specific deep dives (YouTube, IGTV)
  **Tier 3:** Quick insights (Shorts, Reels, TikTok)
  **Tier 4:** Micro-content (Stories, Twitter videos)

  ### Promotion Strategy
  - Sequential release across platforms
  - Cross-platform traffic driving
  - Community building around video content
  - Engagement optimization for each platform

  ## Technical Production Guidelines

  ### Video Specifications
  **YouTube:** 1920x1080, high-quality audio
  **Shorts/Reels/TikTok:** 1080x1920 vertical
  **LinkedIn:** 1920x1080 or 1080x1080 square
  **Instagram Stories:** 1080x1920 with safe zones

  ### Audio Considerations
  - Clean audio extraction from original interview
  - Background music selection for different platforms
  - Sound effect integration for short-form content
  - Accessibility considerations (captions, transcripts)

  ## Content Calendar Integration

  ### Release Schedule
  **Week 1:** Full interview release (YouTube)
  **Week 2:** First deep-dive video + shorts compilation
  **Week 3:** How-to tutorial + social media promotion
  **Week 4:** Behind-the-scenes + community engagement

  ### Platform-Specific Timing
  - YouTube: Consistent weekly schedule
  - TikTok: Daily posting for algorithm optimization
  - Instagram: 3-5 posts per week
  - LinkedIn: 2-3 professional videos per week

  Please ensure all video concepts maintain platform-appropriate tone while maximizing the educational and entertainment value of the original interview content.

  ---
  Prompt by BrassTranscripts (brasstranscripts.com) – Professional AI transcription with 95-98% accuracy.
  ---

  Expert interview transcript:
  [PASTE YOUR TRANSCRIPT HERE]

example_input: "Interview with productivity expert discussing time management, workflow optimization, and team efficiency strategies for entrepreneurs and business leaders."

example_output: |
  ## YouTube Long-Form Strategy

  ### Main Interview Video
  **Title:** "Productivity Expert Reveals the 4-Hour Workday Method (Used by 500+ CEOs)"
  **Description Template:**
  "Discover the counterintuitive productivity system that's helping entrepreneurs reclaim 20+ hours per week while growing their businesses. [Guest Name], who's consulted for Fortune 500 companies, shares the exact framework in this deep-dive conversation.

  🕐 TIMESTAMPS:
  00:00 - Introduction and guest background
  03:45 - The biggest productivity mistake entrepreneurs make
  08:20 - The 4-Hour Workday framework breakdown
  15:30 - Real case study: How one CEO doubled revenue while working less
  22:10 - Tools and systems mentioned in this interview
  28:45 - Common implementation mistakes to avoid"

  **Thumbnail Concept:** Split-screen showing stressed entrepreneur vs. relaxed productive person, with "4-HOUR WORKDAY?" text overlay
  **Tags:** productivity tips, time management, entrepreneur productivity, business efficiency, CEO strategies, work-life balance

  ### Derived Long-Form Videos
  **Video 1:** "The Complete 4-Hour Workday Implementation Guide (Step-by-Step)"
  **Video 2:** "7 Productivity Tools Every Entrepreneur Needs (2024 Review)"
  **Video 3:** "Why Working Harder Is Killing Your Business (Productivity Myths Debunked)"
  **Video 4:** "Behind the Scenes: How I Tested the 4-Hour Workday for 30 Days"

  ## YouTube Shorts Strategy

  ### Short-Form Concepts
  - **"The $2M Productivity Mistake"** - Hook with cost of inefficiency
  - **"4 Hours vs 12 Hours: Same Results"** - Visual comparison
  - **"This Changed Everything"** - Key insight revelation
  - **"Stop Doing These 3 Things"** - Quick mistake rundown
  - **"Productivity Tool Tier List"** - Quick tool rankings

  ## TikTok Strategy

  ### Specific Video Ideas
  - "POV: You just learned the 4-hour workday method" (trending POV format)
  - "Things productive people do differently" (list format)
  - "Plot twist: Working more isn't working" (revelation format)
  - "Day in my life using the 4-hour method" (lifestyle content)

best_practices:
  - "Platform optimization: Tailor video format, length, and style to each platform's unique algorithm and audience behavior"
  - "Content layering: Create multiple videos from single interview to maximize content ROI and audience reach"
  - "Cross-promotion: Use each platform to drive traffic to others while respecting platform-specific best practices"
  - "Engagement focus: Design videos to encourage comments, shares, and discussions rather than passive consumption"

automation:
  api_compatible: true
  batch_processing: true
  output_format: "video_strategy"

  integration_examples:
    - name: "Video Content Pipeline"
      description: "Automate video content creation and scheduling"
      code_snippet: |
        video_strategy = generate_video_strategy(transcript)
        video_pipeline.create_production_schedule(video_strategy)

    - name: "Multi-Platform Distribution"
      description: "Auto-adapt content for different video platforms"
      code_snippet: |
        strategy = create_video_strategy(transcript)
        platform_content = adapt_for_platforms(strategy)
        distribution_tool.schedule_releases(platform_content)

resources:
  blog_post: "https://brasstranscripts.com/blog/content-marketing-ai-toolkit-interview-optimization-prompts#prompt-5-video-content-strategy"
  guide: "https://brasstranscripts.com/ai-prompt-guide"
  upload: "https://brasstranscripts.com/upload"

tags:
  - "video-marketing"
  - "youtube-strategy"
  - "short-form-video"
  - "content-repurposing"
  - "video-optimization"
  - "multi-platform-video"
  - "video-content-creation"