name: "Customer Support and FAQ Generation"
category: "General Content"
difficulty: "Intermediate"
estimated_tokens: "800-1200"
version: "1.2.0"

description: "Transform common questions and discussions into comprehensive customer support resources. Perfect for converting customer interaction recordings, support call transcripts, and help desk sessions into organized FAQ sections, knowledge base articles, and self-service documentation that reduces support burden."

metadata:
  industry: "Customer Support"
  use_cases:
    - "Support call analysis"
    - "Product onboarding"
    - "Technical troubleshooting"
    - "Feature explanation"
    - "Billing and account support"
    - "Integration assistance"

  target_audience:
    - "Customer support managers"
    - "Technical writers"
    - "Product managers"
    - "Customer success teams"
    - "Support documentation specialists"

  prerequisites:
    - "Customer interaction transcript"
    - "Understanding of common issues"
    - "Knowledge of product features"
    - "Familiarity with support processes"

  outputs:
    - "Structured FAQ section"
    - "Knowledge base articles"
    - "Troubleshooting guides"
    - "Process improvement recommendations"

prompt_template: |
  Based on this customer interaction/support call transcript, create comprehensive support documentation:

  ## FAQ Section
  Extract questions asked and provide clear, helpful answers:

  **Q: [Customer question]**
  **A:** [Clear, actionable answer with steps if applicable]

  [Repeat for all questions identified]

  ## Common Issues and Solutions
  - Problem categories identified
  - Step-by-step resolution processes
  - Prevention tips for customers
  - When to escalate to human support

  ## Knowledge Base Article Suggestions
  Identify topics that need dedicated documentation:
  - Article title
  - Key points to cover
  - Target user type
  - Related articles to link to

  ## Process Improvements
  Based on this interaction, suggest:
  - FAQ updates needed
  - Documentation gaps to fill
  - Training topics for support team
  - Product/service clarifications needed

  Support transcript:
  [PASTE YOUR TRANSCRIPT HERE]

example_input: "Customer support call transcript covering transcription accuracy issues, format selection questions, and billing inquiries - typical of common customer support interactions requiring clear documentation."

example_output: |
  ### Customer Support Documentation: Transcription Service FAQ

  **FAQ Section**

  **Q: Why is my transcription accuracy lower than expected?**
  **A:** Transcription accuracy depends primarily on audio quality. To improve accuracy:
  1. Use a good quality microphone (USB or external mic recommended)
  2. Record in a quiet environment with minimal background noise
  3. Speak clearly at a normal pace
  4. Ensure the audio file is not corrupted or compressed heavily
  5. For best results, aim for audio quality at 44.1kHz sample rate or higher

  If you've followed these guidelines and still experience issues, contact our support team with your audio file for analysis.

  **Q: Which transcript format should I choose for my project?**
  **A:** Format selection depends on your intended use:
  - **TXT:** Choose for clean content creation, blog posts, or document writing
  - **JSON:** Select when you need speaker identification or metadata analysis
  - **SRT/VTT:** Use for video projects requiring subtitles or timestamp references

  You can also download multiple formats to test which works best for your workflow.

  **Common Issues and Solutions**

  **Problem Category:** Low Transcription Accuracy
  - **Resolution Process:**
    1. Check original audio quality (clear speech, minimal background noise)
    2. Verify file format is supported (WAV, MP3, M4A, FLAC recommended)
    3. Ensure audio wasn't heavily compressed or low bitrate
    4. Request reprocessing if audio quality is good
  - **Prevention Tips:** Use quality recording equipment, test audio before long recordings
  - **Escalation:** Contact support if accuracy is below 90% with good quality audio

  **Knowledge Base Article Suggestions**

  **Article Title:** "Audio Quality Best Practices for Optimal Transcription Results"
  - **Key Points:** Equipment recommendations, recording environment setup, file format selection
  - **Target User:** New users and content creators
  - **Related Articles:** "Choosing the Right Transcript Format," "Troubleshooting Accuracy Issues"

  **Process Improvements**

  **FAQ Updates Needed:**
  - Add section about processing time variations during peak hours
  - Include more specific audio quality requirements with examples
  - Expand refund policy explanation with step-by-step process
  - Add troubleshooting steps for common browser upload issues

best_practices:
  - "Searchable format: Structure content for easy customer self-service with clear headings and keywords customers would use"
  - "Visual aids: Suggest where screenshots, videos, or diagrams would help clarify complex processes or technical steps"
  - "Escalation paths: Provide clear guidance on when customers should contact human support for complex issues"
  - "Feedback loops: Create systems to continuously improve content based on customer success and ongoing support interactions"

automation:
  api_compatible: true
  batch_processing: true
  output_format: "support_documentation"

  integration_examples:
    - name: "Knowledge Base Integration"
      description: "Auto-update FAQ and help documentation"
      code_snippet: |
        support_docs = generate_support_documentation(transcript)
        knowledge_base.update_articles(support_docs)

    - name: "Support Ticket Analysis"
      description: "Identify common issues for proactive documentation"
      code_snippet: |
        call_analysis = analyze_support_call(transcript)
        common_issues = extract_recurring_problems(call_analysis)
        kb_updates = generate_preventive_documentation(common_issues)

resources:
  blog_post: "https://brasstranscripts.com/blog/powerful-llm-prompts-transcript-optimization#prompt-6-customer-support-and-faq-generation"
  guide: "https://brasstranscripts.com/ai-prompt-guide"
  upload: "https://brasstranscripts.com/upload"

tags:
  - "customer-support"
  - "faq-generation"
  - "knowledge-base"
  - "troubleshooting"
  - "self-service"
  - "support-documentation"
  - "customer-experience"