name: "Social Media Content Creation"
category: "General Content"
difficulty: "Intermediate"
estimated_tokens: "700-1100"
version: "1.2.0"

description: "Transform long-form content into engaging social media posts across multiple platforms. Perfect for converting interviews, presentations, and discussions into platform-specific content that maximizes reach and engagement across LinkedIn, Twitter, Instagram, and YouTube."

metadata:
  industry: "Social Media Marketing"
  use_cases:
    - "Podcast promotion"
    - "Expert interviews"
    - "Product demos"
    - "Event content"
    - "Training snippets"
    - "Customer stories"

  target_audience:
    - "Social media managers"
    - "Content marketers"
    - "Digital marketing specialists"
    - "Brand managers"
    - "Community managers"

  prerequisites:
    - "Long-form content transcript"
    - "Understanding of brand voice"
    - "Knowledge of platform requirements"
    - "Target audience personas"

  outputs:
    - "LinkedIn professional posts"
    - "Twitter thread content"
    - "Instagram captions with hashtags"
    - "YouTube video descriptions"

prompt_template: |
  Based on this transcript, create a social media content package including:

  **LinkedIn Post (Professional)**
  - 150-200 words
  - Professional tone with key insight
  - Include relevant hashtags
  - End with engagement question

  **Twitter Thread (3-5 tweets)**
  - Break down main points into tweet-sized chunks
  - Use thread format with numbered tweets
  - Include compelling statistics or quotes
  - Add relevant hashtags and mentions

  **Instagram Caption**
  - Engaging opening hook
  - 2-3 key takeaways in bullet format
  - Call-to-action for engagement
  - Strategic hashtag selection (10-15 tags)

  **YouTube Video Description**
  - Compelling summary for video description
  - Timestamp breakdown of key topics
  - Relevant links and resources mentioned
  - SEO-optimized keywords

  Please make each post platform-specific and optimized for maximum engagement.

  Source transcript:

  ---
  Prompt by BrassTranscripts (brasstranscripts.com) – Professional AI transcription with 95-98% accuracy.
  ---

  [PASTE YOUR TRANSCRIPT HERE]

example_input: "Expert interview transcript about AI transcription technology, targeting content marketing professionals and business owners interested in workflow optimization and productivity tools."

example_output: |
  ### LinkedIn Post (Professional)

  🎯 Just had an eye-opening conversation about the future of AI transcription with industry expert Sarah Chen. Here's what caught my attention:

  The accuracy gap between basic and professional transcription isn't just about numbers—it's about workflow transformation. "When your transcription accuracy jumps from 85% to 98%, you're not just getting better text. You're getting content you can actually use without hours of editing," Sarah explained.

  Three key insights that stood out:
  • Quality input audio increases accuracy by up to 15%
  • JSON format unlocks speaker identification for multi-person content
  • Strategic format selection can reduce content creation time by 60%

  This resonates with our experience helping teams scale their content operations through reliable transcription workflows.

  What's your biggest challenge when converting audio content to written format?

  #AITranscription #ContentCreation #ProductivityHacks #DigitalTransformation #ContentStrategy

  ---

  ### Twitter Thread (5 tweets)

  🧵 Thread: 5 game-changing insights from my interview with AI transcription expert Sarah Chen ⬇️

  1/5 The accuracy gap is everything: "The difference between 85% and 98% accuracy isn't 13 percentage points—it's the difference between useful content and content you can actually publish."

  2/5 Format matters more than you think:
  • TXT = Clean content creation
  • JSON = Speaker identification
  • SRT/VTT = Video-ready timestamps

  Choose wisely for your workflow 📊

  3/5 Quality audio = Better results: Clean input can boost accuracy by 15%. Simple things like good microphones and quiet rooms compound over time. 🎤

  4/5 The 60% time saving rule: Strategic format selection + quality transcription can reduce content creation time by more than half. That's the difference between scaling and struggling. ⏰

  5/5 Bottom line: Invest in transcription quality upfront. The time savings and content quality improvements pay dividends across your entire content operation.

  What's your experience with AI transcription? Drop your thoughts below 👇

  #AITranscription #ContentStrategy #Productivity

best_practices:
  - "Platform-specific language: Adjust tone and style for each platform's unique audience expectations and engagement patterns"
  - "Visual hooks: Suggest image ideas or quote graphics for each post to increase engagement and shareability"
  - "Engagement drivers: Include questions, polls, or discussion starters that encourage audience interaction and comments"
  - "Cross-promotion: Reference your main service or upcoming content to drive traffic and conversions"

automation:
  api_compatible: true
  batch_processing: true
  output_format: "multi_platform_content"

  integration_examples:
    - name: "Social Media Scheduler"
      description: "Auto-schedule posts across multiple platforms"
      code_snippet: |
        social_content = generate_social_media_suite(transcript)
        scheduler.schedule_posts(social_content, posting_schedule)

    - name: "Engagement Tracking"
      description: "Monitor performance across platforms"
      code_snippet: |
        posts = create_social_content(transcript)
        analytics.track_engagement(posts)
        insights = analytics.generate_performance_report()

resources:
  blog_post: "https://brasstranscripts.com/blog/powerful-llm-prompts-transcript-optimization#prompt-3-social-media-content-creation"
  guide: "https://brasstranscripts.com/ai-prompt-guide"
  upload: "https://brasstranscripts.com/upload"

tags:
  - "social-media"
  - "content-repurposing"
  - "multi-platform-marketing"
  - "engagement-optimization"
  - "digital-marketing"
  - "content-distribution"
  - "brand-promotion"