name: "Transcript Formatting & Style Standardizer"
category: "General Content"
difficulty: "Intermediate"
estimated_tokens: "1000-1500"
version: "1.0.0"

description: "Transform raw AI transcription output into professionally formatted documents following your specific style guide requirements. This prompt applies consistent formatting, grammar, punctuation, speaker labels, and technical notation across entire transcripts."

metadata:
  industry: "Transcription Services"
  use_cases:
    - "Corporate meetings"
    - "Podcast transcripts"
    - "Research interviews"
    - "Video content"
    - "Legal proceedings"
    - "Medical records"

  target_audience:
    - "Business professionals"
    - "Content creators"
    - "Researchers"
    - "Legal professionals"
    - "Medical transcriptionists"

  prerequisites:
    - "Raw AI transcript"
    - "Style guide preferences"
    - "Understanding of verbatim vs clean read"

  outputs:
    - "Professionally formatted transcript"
    - "Consistent style application"
    - "Corrected grammar and punctuation"
    - "Change summary report"

prompt_template: |
  I have a raw AI-generated transcript that needs professional formatting and style standardization. Please help me apply consistent rules and formatting throughout the document:

  **Current Transcript:**
  [PASTE YOUR TRANSCRIPT HERE]

  **Formatting Requirements:**
  - Style preference: [Clean read / Verbatim / Intelligent verbatim]
  - Number formatting: [Spell out 1-9, numerals 10+ / All numerals / All spelled out]
  - Time format: [12-hour with AM/PM / 24-hour / Spelled out]
  - Speaker label format: [Full names / "Speaker 1,2,3" / Role titles]
  - Timestamp frequency: [Every paragraph / Every 30 seconds / None / Custom]

  Please standardize the following throughout the transcript:

  1. **Speaker Labels**
     - Apply consistent format for all speaker identifications
     - Place labels on separate lines before dialogue
     - Ensure no mid-sentence label interruptions

  2. **Grammar and Punctuation**
     - Add proper sentence-ending punctuation
     - Insert commas for natural reading flow (not based on pauses)
     - Correct obvious grammatical errors while preserving speaker voice
     - Apply consistent capitalization rules

  3. **Number and Time Formatting**
     - Standardize all number representations per style guide
     - Format all time references consistently
     - Add commas to large numbers (1,000 not 1000)

  4. **Content Notation**
     - Mark inaudible sections as [inaudible HH:MM:SS]
     - Indicate unclear content as [unclear] or [unclear: best guess?]
     - Note significant non-speech sounds: [laughter], [phone rings]
     - Handle simultaneous speech: [speaking simultaneously]

  5. **Technical Terms and Acronyms**
     - Spell out acronyms on first use: Full Name (ACRONYM)
     - Use acronym alone in subsequent references
     - Verify technical term spellings and correct if needed
     - Flag uncertain terminology for manual review

  6. **Remove or Clean**
     - Remove excessive filler words ("um," "uh," "like") if clean read style
     - Eliminate false starts and repeated words unless verbatim required
     - Clean up run-on sentences into proper sentence structure
     - Remove irrelevant background conversation or noise

  7. **Consistency Checks**
     - Ensure consistent spelling of names, companies, products throughout
     - Verify consistent terminology (don't alternate between synonyms)
     - Apply consistent paragraph breaks at logical conversation points
     - Maintain consistent tense and voice

  Please return the fully formatted transcript with all standardizations applied, and provide a brief summary of major changes made (e.g., "Corrected 47 instances of inconsistent speaker labels, standardized 23 number formats, removed 156 filler words").

  ---
  Prompt by BrassTranscripts (brasstranscripts.com) – Professional AI transcription with professional-grade accuracy.
  ---

example_input: "Raw 60-minute meeting transcript with inconsistent speaker labels, mixed number formatting, and 200+ filler words, requiring clean read style with AP Style number formatting"

example_output: |
  **Formatted Transcript - Board Meeting - October 29, 2025**

  John Smith (CEO): Good morning, everyone. Let's start with Q4 results. Revenue reached $1.2 million, exceeding our target by 15%.

  Sarah Johnson (CFO): That's correct. We saw strong performance in three key areas: enterprise sales increased 23%, recurring revenue grew to $850,000 annually, and customer acquisition costs decreased to $1,200 per customer.

  [phone rings in background]

  John Smith (CEO): [pauses for phone] As I was saying, this positions us well for next quarter.

  **Changes Applied:**
  - Standardized 47 speaker labels (removed mid-sentence switches)
  - Formatted 23 numbers per AP Style (spelled out 1-9, numerals 10+)
  - Removed 156 filler words ("um," "uh," "like")
  - Added 89 punctuation marks for proper sentence structure
  - Corrected 12 grammatical errors while preserving speaker voice
  - Noted 3 background sounds per style guide

best_practices:
  - "Style guide clarity: Specify your style preferences clearly (AP Style, Chicago Manual, internal company standards)"
  - "Verbatim requirements: For legal or medical transcripts, explicitly state verbatim requirements to prevent content removal"
  - "Sample review: After first use, review a sample section to verify formatting matches expectations before processing full document"
  - "Save preferences: Document your style choices for consistent formatting across multiple transcripts"

automation:
  api_compatible: true
  batch_processing: true
  output_format: "formatted_transcript"

  integration_examples:
    - name: "Style Guide Automation"
      description: "Apply company style guide automatically to all transcripts"
      code_snippet: |
        style_config = load_company_style_guide()
        formatted_transcript = standardize_formatting(
          raw_transcript,
          style_config
        )

    - name: "Quality Assurance Pipeline"
      description: "Format and verify transcripts before distribution"
      code_snippet: |
        formatted = apply_style_standardization(transcript)
        quality_score = verify_formatting_consistency(formatted)
        if quality_score > 95:
            approve_for_distribution(formatted)

resources:
  blog_post: "https://brasstranscripts.com/blog/audio-transcription-questions-answered-expert-guide#ai-prompt-2-transcript-formatting--style-standardizer"
  guide: "https://brasstranscripts.com/ai-prompt-guide"
  upload: "https://brasstranscripts.com/upload"

tags:
  - "formatting"
  - "style-guide"
  - "consistency"
  - "grammar-correction"
  - "professional-transcription"
  - "quality-control"
